env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 12
rules: { no-underscore-dangle: off }
plugins:
  - prettier
prettier/prettier: ['error', { 'endOfLine': 'auto' }]
